apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-risk-prediction
  labels:
    app: heart-risk-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-risk-prediction
  template:
    metadata:
      labels:
        app: heart-risk-prediction
    spec:
      containers:
      - name: heart-risk-prediction
        image: 680789327714.dkr.ecr.us-east-1.amazonaws.com/heart-risk-prediction:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"


---
apiVersion: v1
kind: Service
metadata:
  name: heart-risk-prediction-service
spec:
  type: LoadBalancer
  selector:
    app: heart-risk-prediction
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP